### ISSUE TITLE
ta4j-core 0.13-SNAPSHOT这个包下不下来，目前最新的为0.14的， 用0.13或者0.14的的TimeSeries找不到，能否提供下0.13-SNAPSHOT这个jar包

### ISSUE THREAD

**Issue by chenhengtong** [yangyangchu1992/quant4j#16]
ta4j-core 0.13-SNAPSHOT这个包下不下来，目前最新的为0.14的， 用0.13或者0.14的的TimeSeries找不到，能否提供下0.13-SNAPSHOT这个jar包

**Comment by CHENCHEN-MO** [comment]
我也遇到这个问题了，降到0.12可以找到TimeSeries了，但是HighPriceIndicator这个类又找不到了。。。

**Comment by Frank--Sun** [comment]
现在已经编译不过了,怎么才能编译过

**Comment by htn1314** [comment]
我也是，编译都过不了，ta4j-core 0.13-SNAPSHOT这个包下不下来 maven下不下来，大佬帮忙看下

**Comment by yangyangchu1992** [comment]
晚上我回去发下这个包

**Comment by htn1314** [comment]
三克油，大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "MR-yang"<notifications@github.com&gt;; 
发送时间: 2020年12月17日(星期四) 下午2:16
收件人: "yangyangchu1992/quant4j"<quant4j@noreply.github.com&gt;; 
抄送: "韩天宁"<2684537442@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [yangyangchu1992/quant4j] ta4j-core 0.13-SNAPSHOT这个包下不下来，目前最新的为0.14的， 用0.13或者0.14的的TimeSeries找不到，能否提供下0.13-SNAPSHOT这个jar包 (#16)





 
晚上我回去发下这个包

**Comment by yangyangchu1992** [comment]
[0.13-SNAPSHOT.zip](https://github.com/yangyangchu1992/quant4j/files/5718998/0.13-SNAPSHOT.zip)
查看附件

**Comment by blackstrip** [comment]
还差一个`ta4j-parent-0.13-SNAPSHOT`这个版本？能再传一下吗？网上没找到。
`[ERROR] Failed to execute goal on project qt-parent: Could not resolve dependencies for project com.quant:qt-parent:pom:0.0.1-SNAPSHOT: Failed to collect dependencies at org.ta4j:ta4j-core:jar:0.13-SNAPSHOT: Failed to read artifact descriptor for org.ta4j:ta4j-core:jar:0.13-SNAPSHOT: Could not find artifact org.ta4j:ta4j-parent:pom:0.13-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]`

**Comment by yangyangchu1992** [comment]
看关闭的历史问题里，我上传过



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Henry <notifications@github.com&gt;
发送时间: 2021年3月7日 10:43
收件人: yangyangchu1992/quant4j <quant4j@noreply.github.com&gt;
抄送: MR-yang <975965279@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[yangyangchu1992/quant4j] ta4j-core 0.13-SNAPSHOT这个包下不下来，目前最新的为0.14的， 用0.13或者0.14的的TimeSeries找不到，能否提供下0.13-SNAPSHOT这个jar包 (#16)

**Comment by blackstrip** [comment]
> 看关闭的历史问题里，我上传过 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Henry <notifications@github.com&gt; 发送时间: 2021年3月7日 10:43 收件人: yangyangchu1992/quant4j <quant4j@noreply.github.com&gt; 抄送: MR-yang <975965279@qq.com&gt;, State change <state_change@noreply.github.com&gt; 主题: 回复：[yangyangchu1992/quant4j] ta4j-core 0.13-SNAPSHOT这个包下不下来，目前最新的为0.14的， 用0.13或者0.14的的TimeSeries找不到，能否提供下0.13-SNAPSHOT这个jar包 (#16)

搞定了，谢谢
