### ISSUE TITLE
ta4j-core  0.13-SNAPSHOT包依赖问题

### ISSUE THREAD

**Issue by CmZhangxin** [yangyangchu1992/quant4j#21]
ta4j-core  0.13-SNAPSHOT 仓库已经没有了，使用低版本可以有TimeSeries，但是没有HighPriceIndicator和LowPriceIndicator ，使用高版本有HighPriceIndicator，LowPriceIndicator  但是又没有TimeSeries

如何解决？

**Comment by yangyangchu1992** [comment]
在close问题里放了一个jar 包 直接下载
