### ISSUE TITLE
为什么取市场交易的数据

### ISSUE THREAD

**Issue by 15868153548** [yangyangchu1992/quant4j#3]
请问为什么调用这个接口，/market/history/trade，是代表成交的交易记录吧，应该不是盘口的数据。另外实时性方面是不是会不好，为何不调用ws的。请告知，谢谢

**Comment by tokenIsme** [comment]
ws一个账号只能有八个同时链接 多了就不行了。 应该是用深度数据比较好。我一直用的市价，所以没啥影响。限价就有影响了

---原始邮件---
发件人: "2_Fish"<notifications@github.com&gt;
发送时间: 2019年9月18日(星期三) 中午11:17
收件人: "tokenIsme/quant4j"<quant4j@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [tokenIsme/quant4j] 为什么取市场交易的数据 (#3)



请问为什么调用这个接口，/market/history/trade，是代表成交的交易记录吧，应该不是盘口的数据。另外实时性方面是不是会不好，为何不调用ws的。请告知，谢谢
