### ISSUE TITLE
初学者，有交流群吗？

### ISSUE THREAD

**Issue by helxm** [yangyangchu1992/quant4j#5]
求教如何配置策略？或者请给个示例，感谢

**Comment by tokenIsme** [comment]
简单的策略就是设置一堆参数， 指标的策略是先定指标 然后组合他们

**Comment by helxm** [comment]
再请教下权重是指什么？我看您截图配置的购买权重2，卖出权重0，我也按照此配置了试了下，跑了一天，log全是【当前策略计算购买权重:0】

**Comment by yangyangchu1992** [comment]
基于你的条件 对权重的叠加 达到你设置的最终权重 是买还是卖

**Comment by shenyanping** [comment]
有没有交流群啊   有些问题想请教下
