### ISSUE TITLE
环境和安装问题

### ISSUE THREAD

**Issue by moguv587** [yangyangchu1992/quant4j#6]
能大概提示下需要装什么环境吗
目前是jdk1.8,mvn3.6.2,mysql 5.1,redis3.2.12
使用mvn install后进入每个包进行run
java -jar qt-admin-0.0.1-SNAPSHOT.jar

一直报错
烦请更新下readme或者提示下具体安装步骤，谢谢作者

**Comment by yangyangchu1992** [comment]
报啥错？

**Comment by ChengHaiming** [comment]
有最新的前端代码吗？  前端的代码不是最新的呢
