### ISSUE TITLE
ta4j-core依赖里没有TimeSeries这个类

### ISSUE THREAD

**Issue by niukouMan** [yangyangchu1992/quant4j#7]
org.ta4j.core.TimeSeries;

**Comment by helxm** [comment]
我也遇到ta4j的快照版本更新，你依赖这个试试：
<dependency>
            <groupId>org.ta4j</groupId>
            <artifactId>ta4j-core</artifactId>
            <version>0.13-20190907.082949-6</version>
        </dependency>

**Comment by helxm** [comment]
`
<dependency>
            <groupId>org.ta4j</groupId>
            <artifactId>ta4j-core</artifactId>
            <version>0.13-20190907.082949-6</version>
        </dependency>
`

**Comment by yaohuijie** [comment]
org.ta4j.core.TimeSeries;这个类在0.13版本已经删除了，切换成0.12版本就有了。

**Comment by yaohuijie** [comment]
> org.ta4j.core.TimeSeries;这个类在0.13版本已经删除了，切换成0.12版本就有了。

org.ta4j.core.TimeSeries已经重命名TimeSeries为BarSeries，附上链接ta4j的wiki链接：https://ta4j.github.io/ta4j-wiki/Getting-started.html
